chore: add AppImage setup & improve desktop linux support

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,6 +1,8 @@
 name: Release
 
 on:
+  # TODO remove after debug
+  pull_request:
   workflow_dispatch: # manual trigger
 
 permissions:
@@ -12,6 +14,7 @@ env:
 
 jobs:
   version:
+    name: Extract & check version
     runs-on: ubuntu-latest
     outputs:
       version: ${{ steps.get-version.outputs.version }}
@@ -28,18 +31,18 @@ jobs:
         with:
           file: "./PKVault.Backend/PKVault.Backend.csproj"
 
-      - name: Check if version already exist
-        env:
-          VERSION: v${{ steps.get-version.outputs.version }}
-        run: |
-          if git ls-remote --tags origin | grep -q "refs/tags/$VERSION"; then
-            echo "❌ Error: version $VERSION already exist (tag)!"
-            exit 1
-          fi
-          if gh release list | grep -q "$VERSION"; then
-            echo "❌ Error: version $VERSION already exist (release)!"
-            exit 1
-          fi
+      # - name: Check if version already exist
+      #   env:
+      #     VERSION: v${{ steps.get-version.outputs.version }}
+      #   run: |
+      #     if git ls-remote --tags origin | grep -q "refs/tags/$VERSION"; then
+      #       echo "❌ Error: version $VERSION already exist (tag)!"
+      #       exit 1
+      #     fi
+      #     if gh release list | grep -q "$VERSION"; then
+      #       echo "❌ Error: version $VERSION already exist (release)!"
+      #       exit 1
+      #     fi
 
       - name: Compute tag and major/minor
         id: compute
@@ -50,6 +53,7 @@ jobs:
           echo "major_minor=$MAJOR_MINOR" >> $GITHUB_OUTPUT
 
   docker:
+    name: Build & push monolith Docker image
     needs: version
     strategy:
       fail-fast: false
@@ -69,34 +73,35 @@ jobs:
           echo "TAG=${{ needs.version.outputs.tag }}" >> $GITHUB_ENV
           echo "MAJOR_MINOR=${{ needs.version.outputs.major_minor }}" >> $GITHUB_ENV
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+      # - name: Set up Docker Buildx
+      #   uses: docker/setup-buildx-action@v3
 
-      - name: Login to GHCR
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Login to GHCR
+      #   uses: docker/login-action@v3
+      #   with:
+      #     registry: ghcr.io
+      #     username: ${{ github.actor }}
+      #     password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build and push multi-arch image
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          file: ./Dockerfile
-          target: monolith
-          platforms: ${{ matrix.platform }}
-          push: true
-          tags: |
-            ${{ env.REGISTRY_IMAGE_NAME }}:${{ env.TAG }}
-            ${{ env.REGISTRY_IMAGE_NAME }}:${{ env.MAJOR_MINOR }}
-            ${{ env.REGISTRY_IMAGE_NAME }}:latest
-          build-args: |
-            VITE_SERVER_URL=http://localhost:3000
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
+      # - name: Build and push monolith image
+      #   uses: docker/build-push-action@v6
+      #   with:
+      #     context: .
+      #     file: ./Dockerfile
+      #     target: monolith
+      #     platforms: ${{ matrix.platform }}
+      #     push: true
+      #     tags: |
+      #       ${{ env.REGISTRY_IMAGE_NAME }}:${{ env.TAG }}
+      #       ${{ env.REGISTRY_IMAGE_NAME }}:${{ env.MAJOR_MINOR }}
+      #       ${{ env.REGISTRY_IMAGE_NAME }}:latest
+      #     build-args: |
+      #       VITE_SERVER_URL=http://localhost:3000
+      #     cache-from: type=gha
+      #     cache-to: type=gha,mode=max
 
   release:
+    name: Create GitHub release
     needs: [version, docker]
     runs-on: ubuntu-latest
 
@@ -108,16 +113,27 @@ jobs:
           echo "TAG=${{ needs.version.outputs.tag }}" >> $GITHUB_ENV
           echo "VERSION=${{ needs.version.outputs.version }}" >> $GITHUB_ENV
 
-      - name: Build WinForm exe
-        env:
-          TAG: ${{ env.TAG }}
+      - name: Build Win64 desktop image & extract executable
         run: |
-          docker build . --target winform-publish -t tmp-winform
-          docker create --name tmp-winform tmp-winform
-          docker cp tmp-winform:/app/publish/PKVault.exe PKVault.exe
-          docker rm tmp-winform
-          docker rmi tmp-winform
-          ls -la PKVault.exe
+          docker build . --target desktop --build-arg RID=win-x64 -t tmp-desktop-win64
+          docker create --name tmp-desktop-win64 tmp-desktop-win64
+          docker cp tmp-desktop-win64:/app/PKVault.exe PKVault.exe
+
+          docker rm tmp-desktop-win64
+          docker rmi tmp-desktop-win64
+
+          ls -la .
+
+      - name: Build Linux64 desktop image & extract executable
+        run: |
+          docker build . --target desktop --build-arg RID=linux-x64 -t tmp-desktop-linux64
+          docker create --name tmp-desktop-linux64 tmp-desktop-linux64
+          docker cp tmp-desktop-linux64:/app/PKVault.AppImage PKVault.AppImage
+
+          docker rm tmp-desktop-linux64
+          docker rmi tmp-desktop-linux64
+
+          ls -la .
 
       - name: Create tag
         env:
@@ -126,11 +142,16 @@ jobs:
           git tag $VERSION
           git push origin $VERSION
 
-      - name: Create release
-        uses: softprops/action-gh-release@v2
-        with:
-          tag_name: v${{ env.VERSION }}
-          name: v${{ env.VERSION }}
-          generate_release_notes: true
-          files: |
-            PKVault.exe
+      - name: Test desktop files
+        run: |
+          ls -la .
+
+      # - name: Create release
+      #   uses: softprops/action-gh-release@v2
+      #   with:
+      #     tag_name: v${{ env.VERSION }}
+      #     name: v${{ env.VERSION }}
+      #     generate_release_notes: true
+      #     # TODO should include executables from "apps" job
+      #     files: |
+      #       PKVault.exe
